[package]
name = "dao"
version = "0.1.0"
authors = ["SamedhG <gupta.sam@husky.neu.edu>"]
edition = "2018"


[dependencies]
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.9.0"
